kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
    - name: nginx
      image: nginx
resources:
  resquests:
    memory: "70mi"
    cpu: "150m"
  limits:
    memory: "125mi"
    cpu: "180m"
    