kind: ReplicaSet
apiVersion: app/v1
metadata:
  name: nginx
  labels:
    app: frontend
    tier: app
  spec:
    replicas: 3
    selector:
      matchLables:
        app: frontend
        tier: web
    template:
      metadata:
        labels:
          app: frontend
          tier: web
      spec:
        containers:
          - name: nginx
            image: nginx
